server:
  port: 8080
allow:
  annoymous:
    - "/"
#spring:
#  jackson:
#    mapper:
#    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
application:
  jwt:
    secret: "securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure"
    prefix: "Bearer "
    expirationDays: 14
